apiVersion: v1
kind: Namespace
metadata:
  name: app
---
apiVersion: v1
kind: Service
metadata:
  name: producer
  namespace: app
  labels:
    app: producer
spec:
  type: LoadBalancer
  ports:
  - port: 5000
  selector:
    app: producer
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: producer
  namespace: app
  labels:
    app: producer
spec:
  serviceName: producer
  selector:
    matchLabels:
      app: producer
  replicas: 1
  template:
    metadata:
      namespace: app
      labels:
        app: producer
    spec:
      containers:
      - name: master
        image: app:local
        imagePullPolicy: IfNotPresent
        env:
        - name: ASPNETCORE_URLS
          value: "http://*:5000"
        - name: RABBITMQ__HOST
          value: rabbitmq.rabbitmq
        - name: RABBITMQ__PASSWORD
          value: password
        - name: RABBITMQ__USER
          value: admin
        - name: RABBITMQ__EnableConsuming
          value: "false"
        ports:
        - containerPort: 5000
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: consumer
  namespace: app
  labels:
    app: consumer
spec:
  serviceName: consumer
  selector:
    matchLabels:
      app: consumer
  replicas: 1
  template:
    metadata:
      namespace: app
      labels:
        app: consumer
    spec:
      containers:
      - name: master
        image: app:local
        imagePullPolicy: IfNotPresent
        env:
        - name: ASPNETCORE_URLS
          value: "http://*:6000"
        - name: RABBITMQ__HOST
          value: rabbitmq.rabbitmq
        - name: RABBITMQ__PASSWORD
          value: password
        - name: RABBITMQ__USER
          value: admin
        - name: RABBITMQ__EnableConsuming
          value: "true"
        ports:
        - containerPort: 6000
