apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-master
  labels:
    app: rabbitmq
    role: master
    tier: backend
spec:
  type: LoadBalancer
  ports:
  - port: 15672
  selector:
    app: rabbitmq
    role: master
    tier: backend
