apiVersion: v1
kind: Namespace
metadata:
  name: rabbitmq
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: rabbitmq-volume
  namespace: rabbitmq
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  #storageClassName: standard
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: rabbitmq
  labels:
    app: rabbitmq
spec:
  type: LoadBalancer
  ports:
  - port: 15672
    name: web
  - port: 15692
    name: metrics
  selector:
    app: rabbitmq
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rabbitmq
  namespace: rabbitmq
  labels:
    app: rabbitmq
spec:
  serviceName: rabbitmq
  selector:
    matchLabels:
      app: rabbitmq
  replicas: 1
  template:
    metadata:
      labels:
        app: rabbitmq
        namespace: rabbitmq
    spec:
      containers:
      - name: master
        image: rabbitmq:local
        imagePullPolicy: IfNotPresent
        env:
        - name: RABBITMQ_DEFAULT_USER
          value: admin
        - name: RABBITMQ_DEFAULT_PASS
          value: password
        ports:
        - containerPort: 15672
        - containerPort: 5672
        - containerPort: 15692
        volumeMounts:
        - name: rabbitmq-data
          mountPath: /var/lib/rabbitmq
      volumes:
      - name: rabbitmq-data
        persistentVolumeClaim:
          claimName: rabbitmq-volume
